server:
  port: 9091
  servlet:
    context-path: /demo-sp


spring:
  thymeleaf:
    cache: false
  security:
    saml2:
      service-provider:
        alias: demo-sp
        sign-metadata: true
        sign-requests: true
        want-assertions-signed: true
        single-logout-enabled: true
        name-ids:
          - urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
          - urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
          - urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
        keys:
          active:
            name: sp-signing-key-1
            private-key: |
              -----BEGIN RSA PRIVATE KEY-----
              Proc-Type: 4,ENCRYPTED
              DEK-Info: DES-EDE3-CBC,74A35B88C7D896D6

              gYAdG2V0HpIxt+TxmSZ4UEJt+mR2D5tFYxy5sO1L7RuCVMwPOtTWvMLvalvsDOUs
              5+l2Jg1mILKEEN42D3wx4M/GWqa+W7lJ7TG/SZQQLNqWz7iFCvEqFpcnBjKj+PNb
              p4A1mt1dlw4+BsZrf3/C/knG/nV9ZAnK7C21eEB57ok2OLU6MqgGEUDFjKsw72bq
              jm9+9XTDUPXIcNSwQU9ooLas0DaGKHfJsOIm/GAPEmYSc43prunQ86Yu5raU7JPE
              gH00/XVZBI/Jax+BLB4lDt5h3qJy/jOTp6Guhz22vb8otWO7REjYqo+LiPppmmLe
              Gu9cpcSVCjmUzQnZ3TTA9W8ZK22TUjJagKhPl3m49b+wGFYR9ujy8HEeFIp6qP9C
              XAy+S2kHAsvNJXxkQj8p/RbS+ipRpywaouNKsCmk+kWUV2R31qXvhCDd141uREcH
              Gl/KT4lg1hYV/3yVrJN+FJ51vu4e6W4W5XuhSqswgu6j0wTGONhl6yx2eqlKvVsV
              J/+ef0Lm+1pnU0Jl6K/pYk8Y7qgD5jwEfkfZ+twj+6SjFb/bfp7LJPEqvXc5TTU7
              gWNBAQdpt+bI6lun06PgI673FySYCUZpZXGzCJx8w8KH403avlRZ1xbiXBhZA1HT
              T8v7nEju9avijgXTFOjE43GJ1NQFlmaAPf0J3GJqAhjqf567Is2C6+HUQK2yiW/S
              fcfqfmVViL9OAh21wwvk+BQwQlIPRuvWyIS+lnaWZ+P2InOsIcqdhrICHU0ZSbkk
              UNiR5hwLZUvL5AGlW0Wn3bjRwUI02GcFoS5x/C0j0xM=
              -----END RSA PRIVATE KEY-----
            passphrase: saml-sppassword
            certificate: |
              -----BEGIN CERTIFICATE-----
              MIIClTCCAf4CCQD55L5zJ+hKKjANBgkqhkiG9w0BAQsFADCBjjELMAkGA1UEBhMC
              VVMxEzARBgNVBAgMCldhc2hpbmd0b24xEjAQBgNVBAcMCVZhbmNvdXZlcjEdMBsG
              A1UECgwUU3ByaW5nIFNlY3VyaXR5IFNBTUwxEDAOBgNVBAsMB3NhbWwtc3AxJTAj
              BgNVBAMMHHNhbWwtc3Auc3ByaW5nLnNlY3VyaXR5LnNhbWwwHhcNMTgwOTE4MTY1
              NzUyWhcNMjgwOTE1MTY1NzUyWjCBjjELMAkGA1UEBhMCVVMxEzARBgNVBAgMCldh
              c2hpbmd0b24xEjAQBgNVBAcMCVZhbmNvdXZlcjEdMBsGA1UECgwUU3ByaW5nIFNl
              Y3VyaXR5IFNBTUwxEDAOBgNVBAsMB3NhbWwtc3AxJTAjBgNVBAMMHHNhbWwtc3Au
              c3ByaW5nLnNlY3VyaXR5LnNhbWwwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGB
              AOZsaljjZTainfb/oLPtguTSvaD9cIbsHQ1xqGy78WhE6QuIzwaCGGpG7pkcEpak
              KxobQA0dfx0dvtQeLtFqRc7tOmK9x7r1zhn+jwOGTSNukHpTfTudk/kRYKWccfVa
              zhEzEKvGaUetMWT5COziIUl6Egrp0QCLMpzSH6GkhA9zAgMBAAEwDQYJKoZIhvcN
              AQELBQADgYEA2SBUtbOip8aUw+Ka3ebL+zU4PXWpAuvyfeVUuor2yxTp6vFtsjDq
              xNlNQf3CdH2pCo+WHdFfiv0W545RIbsd7gGwxyi60wYR9/ZCBDvX6Ixpz/zQXvIB
              8SjW08OxqOBneKs192mWEMrNJF93TonzJ6GLkDPGazZgqqqCk/qcDjc=
              -----END CERTIFICATE-----
          stand-by:
            - name: key2
              private-key: |
                -----BEGIN RSA PRIVATE KEY-----
                Proc-Type: 4,ENCRYPTED
                DEK-Info: DES-EDE3-CBC,393409C5B5DFA31D

                O40s+E7P75d8OOcfvE3HTNY8gsULhYk7SBdRw50ZklH5G/TZwCxxfoRfPiA4Q1Jf
                bpEHF8BzyLzjXZwYJT5UqaXW/3ozMj7BZ95UfCR0hrxMXQWq4Nak6gFyHh/1focS
                ljzsLoBjyqjCc4BiFPD8uQHVGFv/PttCLydshnAVdSSrFLi0kVsFJMYOmL9ILG6l
                Ld7Sb2ayD0/+1L0lLW8F6IbTtEYAwuA+mX25Imr9JMPKem1YwI1pqUHr8ifq0kd+
                JsoI4Q0Qf2CKv/nfZI5EjqJO34U5podj2zkqN1W3z7dzdTYNOmigq8XVrBiSmT8B
                lE7Ea1GDFol90AeF6ltJWEE6rM6kYzOoModXdK0ozEu4JNnBV/Fu81sOV9zHBs+9
                zqM7jCC16b6n5W2IKGad02GVCBKE0fmIEfhEUsTJw5UJLjNFYF2PkA13Y7jVGZMT
                38MfE3gWcYYOhXVPuMvJ1thXbjXEImg3yH+XHN3RMyups2B1s2JAXYVP2n5zI9pS
                Y3Wt6iXAkKJ0Fiaa/myitUGtL1QvbhBOOfsw9HFuesxzJuKTJ7gqs0ceYwtpQ4X8
                wjk0HXz/riAb+BI6ImEd6H077e/U5u1c9WOdqAKEExAlXL8EhG5Azsj84cCAFuGl
                +T5XVBir0a1jUBQycnsinGZoy3lhE+92j8EhM4LgrDbzoqICVLrk1jX9FiDbcqzZ
                if87phEJmxz+ymCygUjzYohc0sIOwVcMl+s6Y+JsfSBDyg2XEIhzPPdGdgpCrxBg
                KEtaNgtbHXo7UOlN6voWliM14n1g13+xtUuX7hRve3Uy7MMwtuSVJA==
                -----END RSA PRIVATE KEY-----
              passphrase: sppassword
              certificate: |
                -----BEGIN CERTIFICATE-----
                MIICgTCCAeoCCQCQqf5mvKPOpzANBgkqhkiG9w0BAQsFADCBhDELMAkGA1UEBhMC
                VVMxEzARBgNVBAgMCldhc2hpbmd0b24xEjAQBgNVBAcMCVZhbmNvdXZlcjEdMBsG
                A1UECgwUU3ByaW5nIFNlY3VyaXR5IFNBTUwxCzAJBgNVBAsMAnNwMSAwHgYDVQQD
                DBdzcC5zcHJpbmcuc2VjdXJpdHkuc2FtbDAeFw0xODA1MTQxNDQ0NDZaFw0yODA1
                MTExNDQ0NDZaMIGEMQswCQYDVQQGEwJVUzETMBEGA1UECAwKV2FzaGluZ3RvbjES
                MBAGA1UEBwwJVmFuY291dmVyMR0wGwYDVQQKDBRTcHJpbmcgU2VjdXJpdHkgU0FN
                TDELMAkGA1UECwwCc3AxIDAeBgNVBAMMF3NwLnNwcmluZy5zZWN1cml0eS5zYW1s
                MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCXJXpaDE6QmY9eN9pwcG8k/54a
                K9YLzRgln64hZ6mvdK+OIIBB5E2Pgenfc3Pi8pF0B9dGUbbNK8+8L6HcZRT/3aXM
                WlJsENJdMS13pnmSFimsTqoxYnayc2EaHULtvhMvLKf7UPRwX4jzxLanc6R4IcUL
                JZ/dg9gBT5KDlm164wIDAQABMA0GCSqGSIb3DQEBCwUAA4GBAHDyh2B4AZ1C9LSi
                gis+sAiVJIzODsnKg8pIWGI7bcFUK+i/Vj7qlx09ZD/GbrQts87Yp4aq+5OqVqb5
                n6bS8DWB8jHCoHC5HACSBb3J7x/mC0PBsKXA9A8NSFzScErvfD/ACjWg3DJEghxn
                lqAVTm/DQX/t8kNTdrLdlzsYTuE0
                -----END CERTIFICATE-----
            - name: key3
              private-key: |
                -----BEGIN RSA PRIVATE KEY-----
                Proc-Type: 4,ENCRYPTED
                DEK-Info: DES-EDE3-CBC,EF0A6B6E2C665851

                UQ4gDBIOTrksMOLT2fXiqfcD3wpWT54jWhWq0fls8mLz65FU7/LY2dwATGmcCJrU
                N6T9E8mmqbWO8gCKVEx8zBKHOAh9wJVJKVl7aDmHWFYDU1xyighg1GB468ZIqx4/
                dFMY75hxNrOVNbicKcH1XKfn/GtJavbDon9L870l3X2cLFEIUiZGWFcTd8mAWHHY
                d9IHgVQhwE2jBG9wnywO3FEKecwmo5m+VZsTQGWuZIYHSPhNcsoeEg+OViJGaFzi
                xcbW1h+bIG6B3tIdXB7QIf79VPoW7vpXhCvl9+iMk6Tb3JhvnPEulPykiB8xsmzh
                jqr0qc+eYmdTBjmYA5DPuICjo1YLNUZdys8AAe9qyXMU2baPiOsEwcBN1J1oXm/f
                2v5IQX4aNq4KI0SowdNCSv/4txUwbyxGfHcTa+Jy1MbDKV8ggaHYQ1k76mLryRfZ
                3JN937KLmArF6wK2JVO/VkGM1JWdlxcmcYpBGN0lCxFz5qIcMdQT08amCXyfk8Ov
                KX5pFXXFNItFwXJW/tsZNfBiOPP2b7MLjxKuWvVm4SL0aOZG6NuOkZBnJ6AT7jIk
                XTX7csdT/ogOrQrQiSeISeUUGgRULdHZLCgRQ4yVm58FE6QytFcuNddK0f527zr2
                3qrRHT5153693p7Zb/FupEBlPK5yf3jpLKPGZTor1r5QQHsOE60nsZIhz4VtmNj8
                f5+mgpFJ+s6UbkCqOFiE4FTbiWTvIX2K9Ho29FnnTPeLkaq9H4onFAAv2JM2JYEB
                Mz8ZcX+KkiaArqIOvWgqCfLY4taF5XOPaU4/UGUXUUW4lQFw/0+0cw==
                -----END RSA PRIVATE KEY-----
              passphrase: sppassword
              certificate: |
                -----BEGIN CERTIFICATE-----
                MIICgTCCAeoCCQC3dvhia5XvzjANBgkqhkiG9w0BAQsFADCBhDELMAkGA1UEBhMC
                VVMxEzARBgNVBAgMCldhc2hpbmd0b24xEjAQBgNVBAcMCVZhbmNvdXZlcjEdMBsG
                A1UECgwUU3ByaW5nIFNlY3VyaXR5IFNBTUwxCzAJBgNVBAsMAnNwMSAwHgYDVQQD
                DBdzcC5zcHJpbmcuc2VjdXJpdHkuc2FtbDAeFw0xODA1MTQxNDQ1MzBaFw0yODA1
                MTExNDQ1MzBaMIGEMQswCQYDVQQGEwJVUzETMBEGA1UECAwKV2FzaGluZ3RvbjES
                MBAGA1UEBwwJVmFuY291dmVyMR0wGwYDVQQKDBRTcHJpbmcgU2VjdXJpdHkgU0FN
                TDELMAkGA1UECwwCc3AxIDAeBgNVBAMMF3NwLnNwcmluZy5zZWN1cml0eS5zYW1s
                MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC2iAUrJXrHaSOWrU95v8GUGVVl
                5vWrYrNRFtsK5qkhB/nRbL08CbqIeD4pkJuIg0LuJdsBuMtYqOnhQSFF5tT36OId
                ld9SfPA5m8zqPLsCcjWPQ66xoMdReEXN9E8s/mZOXn3jkKIqywUxJ+wkS5qoBlvm
                ShwDff+igFlF/fBfpwIDAQABMA0GCSqGSIb3DQEBCwUAA4GBACDBjvIpc1/2yZ3T
                Qe29bKif5pr/3NdKz4MWBJ6vjRk7Bs2hbPrM2ajxLbqPx6PRPeTOw5XZgrufDj9H
                mrvKHM2LZTp/cIUpxcNpVRyDA4iVNDc7V3qszaWP9ZIswAYnvmyDL2UHVDLE8xoG
                z/AkxsRNN9VXNHewjQO605umiAKJ
                -----END CERTIFICATE-----

        providers:
        - alias: spring-security-saml-idp
          metadata: http://localhost:9092/demo-idp/saml/idp/metadata
          link-text: Spring Security SAML IDP (local)
          name-id: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
          assertion-consumer-service-index: 0
        - alias: simplesamlphp
          metadata: http://saml-s1-2018.cfapps.io/saml2/idp/metadata.php
          link-text: Simple SAML PHP IDP on Cloud Foundry
        - alias: spring-security-saml-idp-sp
          metadata: http://localhost:9093/demo-idp-sp/saml/idp/metadata
          link-text: Spring Security Combo IDP/SP (local)
          name-id: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
